In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
lst = np.array([10,20,30,40,50])

In [3]:
lst

array([10, 20, 30, 40, 50])

In [4]:
type(lst)

numpy.ndarray

In [5]:
lst*3

array([ 30,  60,  90, 120, 150])

In [6]:
lst

array([10, 20, 30, 40, 50])

In [7]:
a1 = np.array([10,20,30,40,50])

In [8]:
b1= np.array([1,2,3,4,5])

In [9]:
c1 = a1+b1

In [10]:
c1

array([11, 22, 33, 44, 55])

In [11]:
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])

In [12]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [13]:
type(a2)

numpy.ndarray

In [14]:
a2.ndim

2

In [15]:
b2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
a2.shape

(2, 3)

In [17]:
b2.shape

(3, 3)

In [18]:
a1.shape

(5,)

In [19]:
a2.shape

(2, 3)

In [20]:
b2.shape

(3, 3)

In [21]:
a1.ndim

1

In [22]:
a2.ndim

2

In [23]:
b2.ndim

2

In [24]:
a1.dtype

dtype('int64')

In [25]:
a2.dtype

dtype('float64')

In [26]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [27]:
a1.size

5

In [28]:
a2.size

6

In [29]:
type(a1)

numpy.ndarray

In [30]:
type(a2)

numpy.ndarray

In [31]:
type(b2)

numpy.ndarray

In [32]:
df = pd.DataFrame(a1)

In [33]:
df

0
0  10
1  20
2  30
3  40
4  50

In [34]:
df = pd.DataFrame(a2)

In [35]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [36]:
df = pd.DataFrame(b2)

In [37]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9