In [2]:
import numpy as np

In [3]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
a1 = np.array([10,20,30,40,50])

In [6]:
print(type(a1))

<class 'numpy.ndarray'>


In [7]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
np.arange(21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
np.linspace(1,6)

array([1.        , 1.10204082, 1.20408163, 1.30612245, 1.40816327,
       1.51020408, 1.6122449 , 1.71428571, 1.81632653, 1.91836735,
       2.02040816, 2.12244898, 2.2244898 , 2.32653061, 2.42857143,
       2.53061224, 2.63265306, 2.73469388, 2.83673469, 2.93877551,
       3.04081633, 3.14285714, 3.24489796, 3.34693878, 3.44897959,
       3.55102041, 3.65306122, 3.75510204, 3.85714286, 3.95918367,
       4.06122449, 4.16326531, 4.26530612, 4.36734694, 4.46938776,
       4.57142857, 4.67346939, 4.7755102 , 4.87755102, 4.97959184,
       5.08163265, 5.18367347, 5.28571429, 5.3877551 , 5.48979592,
       5.59183673, 5.69387755, 5.79591837, 5.89795918, 6.        ])

In [12]:
a1 = np.array([10,20,30,40,50])

In [13]:
a2 = a1.view()

In [14]:
a2

array([10, 20, 30, 40, 50])

In [17]:
a1=a1+np.arange(5)

In [18]:
a1

array([10, 21, 32, 43, 54])

In [19]:
a2

array([10, 20, 30, 40, 50])

In [22]:
a1=np.array([10,20,30])

In [23]:
a1

array([10, 20, 30])

In [24]:
a2 = np.array([100,200,300])

In [25]:
np.sum(a1)

np.int64(60)

In [26]:
w = np.array([1.0,2.5,3.4])
x = np.array([10,20,30])
b= 10

In [28]:
np.dot(w,x) + b

np.float64(172.0)

In [29]:
np.zeros(4)

array([0., 0., 0., 0.])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.random.random_sample(4)

array([0.81602118, 0.21229234, 0.99625172, 0.51159096])

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.random.rand(4)

array([0.56341308, 0.10268994, 0.26805832, 0.14885658])

In [34]:
np.array([2,12,4,3])

array([ 2, 12,  4,  3])

In [35]:
np.array([[12,2,4],[23,12,1]])

array([[12,  2,  4],
       [23, 12,  1]])

In [37]:
a1 = np.arange(11)

In [38]:
a1[3:6]

array([3, 4, 5])

In [39]:
a1[1::2]

array([1, 3, 5, 7, 9])

In [40]:
np.sum(a1)

np.int64(55)

In [41]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
np.mean(a1)

np.float64(5.0)

In [43]:
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [44]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
b1 = np.arange(11)

In [46]:
np.dot(a1,b1)

np.int64(385)

In [47]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
b1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
a1.shape

(11,)

In [50]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
a1 = np.array([[1,2,4,4],[3,23,21,3]])

In [55]:
a1.shape

(2, 4)

In [56]:
a1

array([[ 1,  2,  4,  4],
       [ 3, 23, 21,  3]])

In [59]:
a1 = np.arange(10).reshape(5,2)

In [60]:
a1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [61]:
a1.shape

(5, 2)

In [62]:
a1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [63]:
np.sum(a1)

np.int64(45)